### ISSUE TITLE
Improve mobile UI

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#10]
The UI on mobile could do with some tweaking. For example, there is a large left margin and a small right margin. On my mobile some of the font awesome icons look quite different to on desktop (in a bad way)

**Comment by brucejames** [comment]
Some initial improvements done to the details and participants areas

**Comment by brucejames** [comment]
I'm in process of making these changes:
1. Tidy up navbar display and behaviour for various display sizes
2. Fix "All trips" exceeding display width (=> horiz scroll bar)
3. Tidy up Calendar display
4. Improve Calendar filters 
5. Make dropdowns (e.g. "Grade" ) work better
6. Improve initial loading display

**Comment by brucejames** [comment]
Changes to better work in an iframe have been done.

Some further fine tuning to do....
- Calendar width
- What to do about tooltips?
- Some controls overlapped on small displays
- [Done] Modal map editor dialog can be out of view (need to scroll up)
- Navbar font changes size on mobile
- Trip details 15px too wide causes horiz scrollbar

**Comment by brucejames** [comment]
Still the question about what to do about tooltips.... but closing this for now.
