### ISSUE TITLE
Test triphub in safari

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#100]
Max DeLacey reported that triphub no longer works on safari. It stopping working seemed to coincide with the deployment of the pwa branch, and it's probably just a caching issue (he resolved it by switching to chrome), but we should double check.

**Comment by brucejames** [comment]
Issue is navigator.permissions is undefined. Permissions is only available on Safari >= 16.
Also, window.matchMedia('(display-mode: standalone)').addEventListener is undefined in ealrier Safari versions.

**Comment by brucejames** [comment]
Fixes deployed to production
