### ISSUE TITLE
Can't modify "Open Date" or "Close Date" 

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#101]
On trips that have already been saved, it is not possible to change the "Open Date" or "Close Date" . With sufficient privileges (e.g. Leader/Admin) you can change the dates in the calendar control, however on changing the date nothing is POSTed to the API so the date change doesn't get recorded. Changing other fields, including the trip date, works correctly.

**Comment by brucejames** [comment]
Problem was with the InputControl when inputting a date.  Original value is remembered when control first gets focus in order to filter out unnecessary saves when it looses focus.  Unfortunately, the date dropdown causes another onFocus event which causes the remembered original value to get lost.

**Comment by brucejames** [comment]
Fixed
