### ISSUE TITLE
Manually entering dates doesn't always work

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#106]
On https://ctc.org.nz/triphub-staging, if I manually try and type in a date only the last typed character is saved as an input. E.g, if I select the "day" part, and type 21, then the day is set to 01. Sometimes I can get it to work correctly, e.g. if I type "221" the date gets set to 21, but this is quite unintuitive

**Comment by brucejames** [comment]
Due to a workaround I made in Nov-22 (2e637d7) for Firefox numeric up/down focus issue.  Moved workaround to only apply for number types.

**Comment by nickcedwards** [comment]
Thanks Bruce!
