### ISSUE TITLE
Change new trip creation so that it clones a trip based on short description

### ISSUE THREAD

**Issue by alastairgbrown** [ctcit/triphub#110]
For example typing "Mt Oxford" in the description of a new trip and clicking on the "Search Past Trips" button will result in a popup list of matching past trips.  Clicking on a trip will copy relevant details to the new trip.

**Comment by brucejames** [comment]
Got it working.  But it seemed rather clunky, mostly because there can be quite a few matching past trips and it is difficult to choose one from just the name (and even date, leader) alone.  I stashed it in the end.
