### ISSUE TITLE
JSON database entries not handled correctly

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#12]
Alastair recently changed some fo the database fields to be JSON, but these aren't always handled correctly in the app. Need to either change these fields back to strings or fix the problems.

**Comment by nickcedwards** [comment]
I think this is mainly fixed now, but the `maps` field in `triphub.trips` is still json. Is it just a case of changing the MySQL type to varchar, or are there code changes needed too?

**Comment by brucejames** [comment]
There were a couple of further fixes required for JSON field handling in the PHP.  Also the maps and routes (was mapRoute) fields now are JSON. Client has been changed accordingly.
