### ISSUE TITLE
Triphub crashes when expanding trip history

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#31]
Happens for all trips.

Stacktrace:
```
History.tsx:68 Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at e.render (History.tsx:68)
    at $a (react-dom.production.min.js:181)
    at Ka (react-dom.production.min.js:180)
    at ks (react-dom.production.min.js:261)
    at ku (react-dom.production.min.js:230)
    at Tu (react-dom.production.min.js:229)
    at vu (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at e.unstable_runWithPriority (scheduler.production.min.js:18)
```

**Comment by brucejames** [comment]
Lines 65-68 of History.tsx....

        if (action === 'Email') {
            title = [<span key='1' className='fa fa-paper-plane'/>,' ',action]
            const rows = []
            const values = JSON.parse(item.after || "{}");

Here item.after is an object, not a string.  I suspect the HTML string (representing the email content) has miraculously been translated into JSON somewhere along the linem rather than being left as a string!

**Comment by nickcedwards** [comment]
Yup exactly - for emails, item.after is an object describing the email (not just the html string). Since the API responds as application/json this is already a JS object with no parsing needed - the problem is the typescript interface coerced it to string. Fixed by marking the type as "string | object" and removing the unnecessary call to JSON.parse
