### ISSUE TITLE
Autofilling new members details does not work consistently

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#42]
When adding a non-member to the trip, if the non-member has been on a trip previously triphub should remember and auto-fill their details (email, phone, emergency contact details). Users have reported this does not work consistently. See also #39

**Comment by alastairgbrown** [comment]
The member name control needs changing to a drop down

**Comment by nickcedwards** [comment]
The new control looks really nice, but when I tried to use it on https://ctc.org.nz/index.php/trip-signup#/trips/4193 and selected "John Kerkhofs" it added "Kate Taylor", the trip leader again. I tried this twice, and both times it added Kate again

**Comment by nickcedwards** [comment]
Fixed in 31e9d8d
