### ISSUE TITLE
Improve date formatting in Newsletter

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#46]
From Peter:

>  Dates on headings are still a bit nerdy eg
>  2021-02-05
> 
> Departure point: Z Station Russley 
> 
> which I rewrite to a more readable style like Friday 5 February 2021.

**Comment by alastairgbrown** [comment]
All the logic from the MakeDateDisplay javascript function in newsletter/newsletter.events.php  needs to be rewritten into the triphub.vnl_events view in MySQL in a big ugly case clause.  We might want to consider creating a repo for SQL tables and views .

**Comment by alastairgbrown** [comment]
Added a new MySQL function called date_display that has the necessary logic, and incorporated this into the vnl_events view
