### ISSUE TITLE
Logistic info not being saved

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#52]
> I've noticed on the last couple of trips I've created that the Logistic Information panel isn't being saved, neither when creating the trip, nor when updating later.  Not a major problem as the info can go in the description, but I didn't notice on the first trip I posted and wondered why people weren’t following the instructions.

**Comment by alastairgbrown** [comment]
I think it's a typo here in `logisticnfo`:
```html
                        <TextAreaInputControl id='logisticnfo' label='Logistic Information'
                            helpText='Any additional information related to travel, accomodation etc' {...common}/>
```
