### ISSUE TITLE
Socials not shown in trip list / social list on the day of social

### ISSUE THREAD

**Issue by nickcedwards** [ctcit/triphub#53]
Socials get categorised as "closed" and don't show up on the day of the social. Since socials are generally in the evening, and users may wish to check the website on the day to see what the evening's social is, they should still be visible on the day of the social

**Comment by alastairgbrown** [comment]
Need to change the code from trip.tsx below so that there's no difference between tripdate and closedate for social events
```javascript
        const offset = (this.props.isNewSocial) ? 9 : 12
        const closeDate : Date = AddDays(openDate, offset - openDate.getDay())
        // The day after the close date (a Saturday)
        const tripDate : Date = AddDays(closeDate, 1)
```

**Comment by nickcedwards** [comment]
Slightly more complicated than the change you suggested Alastair, but fixed now
