### ISSUE TITLE
Log table is getting ridiculously big. should we make logging to it configurable?

### ISSUE THREAD

**Issue by alastairgbrown** [ctcit/triphub#78]

**Comment by brucejames** [comment]
Or auto-purge records older than several months?

**Comment by nickcedwards** [comment]
Did someone do something about this? There are still over 1,000,000 rows in that table, but the oldest entry is 2nd March 2023.

**Comment by brucejames** [comment]
I haven't changed anything.

Is the table configured somehow to a limit of approx 1 million rows?  Could see any such setting.

Bruce
________________________________

**Comment by nickcedwards** [comment]
The API endpoints "POST trips/emails" and "POST maintenance/regular" trim the databse to 10,000 lines when queried. However, the server doesn't call these the cronjob calls PostEmails($con) directly. Easiest thing is to modify that method to prune the databse.

**Comment by alastairgbrown** [comment]
Implemented with feature/logging
