### ISSUE TITLE
Investigate 'Can't perform a React state update on an unmounted component" warning after deleting a participant from a trip

### ISSUE THREAD

**Issue by brucejames** [ctcit/triphub#85]
Noticed this after deleting a participant from a trip.   Needs tidying up.

index.js:2178 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in TripParticipant (created by TripParticipants)

**Comment by nickcedwards** [comment]
Doesn't seem to be happening any more, or if it is it isn't causing any problems
